[app]
language = "fr"

[ffmpeg]
fetch_url = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip"
auto_install = true
bin_dir = "./bin"

[updates]
check_on_startup = true

[tui.browser.columns]
fichier = 50
resolution = 14
duree = 9
debit = 10
codec = 10
dolby_vision = 12
decision = 24
audio = 24

[tui.dryrun.columns]
fichier = 42
conteneur = 16
