[serie_anime]
bitrate_720p_kbps = 1500
bitrate_1080p_kbps = 2000
bitrate_4k_kbps = 3500
keep_4k = false
delete_source = false
preset_encoder = "fast"
dolby_vision = "sdr"
preserve_hd_audio = false
audio_languages = [
    "fre",
    "eng",
]
audio_stereo_kbps = 192
audio_surround_kbps = 448
audio_surround_7_1_kbps = 640
audio_copy_compatible = true

[serie_basic]
bitrate_720p_kbps = 1500
bitrate_1080p_kbps = 2200
bitrate_4k_kbps = 5000
keep_4k = false
delete_source = false
preset_encoder = "medium"
dolby_vision = "hdr10"
preserve_hd_audio = false
audio_languages = [
    "fre",
    "eng",
]
audio_stereo_kbps = 192
audio_surround_kbps = 448
audio_surround_7_1_kbps = 640
audio_copy_compatible = true

[serie_hd]
bitrate_720p_kbps = 1500
bitrate_1080p_kbps = 2500
bitrate_4k_kbps = 5000
keep_4k = false
delete_source = false
preset_encoder = "medium"
dolby_vision = "hdr10"
preserve_hd_audio = false
audio_languages = [
    "fre",
    "eng",
]
audio_stereo_kbps = 192
audio_surround_kbps = 448
audio_surround_7_1_kbps = 640
audio_copy_compatible = true

[film_basic]
bitrate_720p_kbps = 2000
bitrate_1080p_kbps = 3000
bitrate_4k_kbps = 5000
keep_4k = false
delete_source = false
preset_encoder = "medium"
dolby_vision = "sdr"
preserve_hd_audio = false
audio_languages = [
    "fre",
    "eng",
]
audio_stereo_kbps = 192
audio_surround_kbps = 448
audio_surround_7_1_kbps = 640
audio_copy_compatible = true

[film_hd]
bitrate_720p_kbps = 3000
bitrate_1080p_kbps = 5000
bitrate_4k_kbps = 8000
keep_4k = false
delete_source = false
preset_encoder = "slow"
dolby_vision = "hdr10"
preserve_hd_audio = true
audio_languages = [
    "fre",
    "eng",
]
audio_stereo_kbps = 192
audio_surround_kbps = 448
audio_surround_7_1_kbps = 640
audio_copy_compatible = true

[cinema_4k_basic]
bitrate_720p_kbps = 2000
bitrate_1080p_kbps = 5000
bitrate_4k_kbps = 8000
keep_4k = true
delete_source = false
preset_encoder = "slow"
dolby_vision = "hdr10"
preserve_hd_audio = true
audio_languages = [
    "fre",
    "eng",
]
audio_stereo_kbps = 192
audio_surround_kbps = 448
audio_surround_7_1_kbps = 640
audio_copy_compatible = true

[cinema_4k_hd]
bitrate_720p_kbps = 2000
bitrate_1080p_kbps = 5000
bitrate_4k_kbps = 12000
keep_4k = true
delete_source = false
preset_encoder = "slow"
dolby_vision = "dv"
preserve_hd_audio = true
audio_languages = [
    "fre",
    "eng",
]
audio_stereo_kbps = 192
audio_surround_kbps = 448
audio_surround_7_1_kbps = 640
audio_copy_compatible = true

[basic_delete]
bitrate_720p_kbps = 1500
bitrate_1080p_kbps = 2000
bitrate_4k_kbps = 3500
keep_4k = false
delete_source = true
preset_encoder = "fast"
dolby_vision = "sdr"
preserve_hd_audio = false
audio_languages = [
    "fre",
    "eng",
]
audio_stereo_kbps = 192
audio_surround_kbps = 448
audio_surround_7_1_kbps = 640
audio_copy_compatible = true
